### ISSUE TITLE
要自己打包吗？不太会

### ISSUE THREAD

**Issue by 14790897** [Fishyet/Seer2AndroidApp#1]

**Comment by Fishyet** [comment]
app分支的out目录下有安装包哦,可以体验一下,看看还有什么bug
自己用idea打包也是可以的,上方的构建选项里面可以自动打包air应用程序
注意: 不要传播安装包,不要在群聊里太多宣扬!!!

**Comment by 14790897** [comment]
好的
![image](https://github.com/Fishyet/Seer2AndroidApp/assets/121866954/2e34fe46-3ba6-41c3-910d-935d91be23cc)

我是看到他点星了，来看看是什么

试玩了一下，还可以

**Comment by Fishyet** [comment]
嘿嘿，发现bug可以和我说。在q群里直接@我就可以，GitHub上连接不太稳定，有点麻烦
